layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: imtrinity94
  # keybase: your_username
  linkedin: mayankgoyal1994
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: imtrinity94
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: imtrinity94

topics:
  - name: vRealize Orchestrator
    web_url: https://www.vmware.com/in/products/vrealize-orchestrator.html
    image_url: https://github.com/imtrinity94/imtrinity94.github.io/blob/master/images.png

  - name: vSphere
    web_url: https://www.vmware.com/in/products/vsphere.html
    image_url: https://github.com/imtrinity94/imtrinity94.github.io/blob/master/VMware-vSphere-7.jpg

  - name: Javascript
    web_url: https://www.javascript.com/
    image_url: https://github.com/imtrinity94/imtrinity94.github.io/blob/master/js_800x800.jpg
