layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: imtrinity94
  # hackerrank: your_username
  instagram: imtrinity94
  # keybase: your_username
  linkedin: mayankgoyal1994
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 16106917
  telegram: imtrinity94
  twitter: imtrinity94
  unsplash: imtrinity94
  # vk: your_username
  website: https://cloudblogger2021.wordpress.com
  youtube: imtrinity94
  soundcloud: imtrinity94

topics:
  - name: vRealize Orchestrator
    web_url: https://www.vmware.com/in/products/vrealize-orchestrator.html
    image_url: https://user-images.githubusercontent.com/7029361/121565185-df1b7f80-ca39-11eb-804e-51f5e917d1ec.png

  - name: vSphere
    web_url: https://www.vmware.com/in/products/vsphere.html
    image_url: https://user-images.githubusercontent.com/7029361/121565199-e2af0680-ca39-11eb-9d72-255e1b435170.jpg

  - name: Cloud Director
    web_url: https://www.vmware.com/in/products/cloud-director.html
    image_url: https://github.com/imtrinity94/imtrinity94.github.io/raw/master/VCDA-Logo-removebg-preview.png
    
