layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: imtrinity94
  # keybase: your_username
  linkedin: mayankgoyal1994
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 16106917
  # telegram: your_username
  twitter: imtrinity94
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: imtrinity94
  # soundcloud: imtrinity94

topics:
  - name: vRealize Orchestrator
    web_url: https://www.vmware.com/in/products/vrealize-orchestrator.html
    image_url: https://user-images.githubusercontent.com/7029361/121565185-df1b7f80-ca39-11eb-804e-51f5e917d1ec.png

  - name: vSphere
    web_url: https://www.vmware.com/in/products/vsphere.html
    image_url: https://user-images.githubusercontent.com/7029361/121565199-e2af0680-ca39-11eb-9d72-255e1b435170.jpg

  - name: Javascript
    web_url: https://www.javascript.com/
    image_url: https://user-images.githubusercontent.com/7029361/121565051-b7c4b280-ca39-11eb-9606-08c484c86025.jpg
